[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["cd backend && npm install --production=false"]

[phases.build]
cmds = ["cd backend && npm run build"]

[start]
cmd = "cd backend && NODE_ENV=production npm start"
